### PR TITLE
Adds `checked_new` API

### PR DESCRIPTION
**Pull request by dilawar**
It return `Option<Self>`. Useful when we can't afford to panic.

### CODE REVIEW

**Comment by ostrosco** [comment]
I think this is the right approach to this. Thanks for the PR!

**Comment by tbakerx** [comment]
Is there a release to crates.io planned following this?

**Comment by ostrosco** [comment]
Yes, sorry. I'm finishing up a 2.0 release soon.

**Comment by tbakerx** [comment]
> Yes, sorry. I'm finishing up a 2.0 release soon.

Saw the release went out, much appreciated 🙏🏼 !

**Pull request merged**
