### PR TITLE
feat: add Numpad support

### LINKED ISSUE #29: Numpad implementation issues
I'm currently implementing Numpad support but there are some keys which technically can be found twice on a standard keyboard:

- PLUS vs Numpad PLUS
- MINUS vs Numpad MINUS

as well as overlapping keys:

- SHIFT+7 vs Numpad DIVIDE
- SHIFT+8 vs Numpad MULTIPLY
- COMMA or DOT (dependent on the _locale / keyboard layout(!)_) vs Numpad SEPERATOR

Should nearly identical keys be merged or this too high-level for this crate?

### PR DESCRIPTION
**Pull request by macbrayne**
Add support for capturing numpad specific key events.
Fixes #29.

### CODE REVIEW

**Comment by macbrayne** [comment]
Testing is needed with MacOS and Linux

**Comment by macbrayne** [comment]
@ostrosco Are the naming conventions in this project more leaning towards Windows or Linux/MacOS? In Windows it's called "numpad", in Linux/MacOS "keypad" but in the end it probably doesn't make a huge difference.

**Comment by macbrayne** [comment]
Fixes #29

**Comment by ostrosco** [comment]
I'm so sorry for leaving this out for so long; real life had really gotten in the way. This all looks great and I'm perfectly happy with the naming convention of `numpad`. Thanks for the PR and sorry for taking so long to accept it.

**Pull request merged**
