### PR TITLE
Events

### PR DESCRIPTION
**Pull request by notdanilo**

### CODE REVIEW

**Comment by ostrosco** [comment]
Hey I see this PR is still a draft, but I really like this idea! The use case is very clear. Once it's ready, I'll take a look and we'll see about getting this merged in.

**Comment by notdanilo** [comment]
@ostrosco cool! I will take some time to finish it asap

**Comment by notdanilo** [comment]
@ostrosco there you go. It's fully implemented. I used some good practices such as using callback guards. It also uses two different threads: one for the mouse and the other for the keyboard. The code is pretty clean and self-explanatory.

**Review by ostrosco — CHANGES_REQUESTED** [review]
Sorry it's taken me so long to get around to this. Been a crazy couple of weeks.

This looks pretty good IMO. One thing I would like done before merging is to have `cargo fmt` and `cargo clippy` run on it and fix everything that pops up.

I also think we should future-proof the code base with the drain_filter. My gut would be to specify the `utils` module on those calls so we can avoid the lints (or rename it, despite me agreeing that the name is correct).

**Comment by notdanilo** [comment]
@ostrosco it should be good now.

**Review by ostrosco — APPROVED** [review]
I like it. Thanks for all your hard work on this! It's really appreciated!

**Pull request merged**
